apiVersion: apps/v1
kind: Deployment                    #create deployment
metadata:
  name: declarative-deployment
  labels:
    app: go-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: dqqm/lesson1:v0.2
        ports:
        - containerPort: 8080