apiVersion: v1
kind: Service                                #create Service позволяет подам обращаться к другим приложениям и другим приложениям к Подам
metadata:
  namespace: namespace-lesson1-4             #указали имя namespace который создали в файле lesson1-4
  name: my-service
spec:
  selector:
    app: labels-app-lesson1-4-1              #в файле lesson1-4-1 поду была присвоена мета, Service найдет этот Под как по этой метке, так как она у него указана в Селекторе
  ports:
    - protocol: TCP
      port: 80                               #позволяет прокидывать любой порт на любой. 
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-balancer
  namespace: namespace-lesson1-4             #указали имя namespace который создали в файле lesson1-4
spec:
  ports:
  - port: 80
    name: webport
    targetPort: 8080
  selector:
    app: labels-app-lesson1-4-1
  type: LoadBalancer                        #позволяет открыть внешний доступ и жестко привязать внешний IP адрес к Поду
  loadBalancerIP: localhost
---
apiVersion: v1
kind: Service
metadata: 
 name: nodeport-goapp-service
 namespace: namespace-lesson1-4            #указали имя namespace который создали в файле lesson1-4
spec:
 type: NodePort
 selector:   
   app: labels-app-lesson1-4
 ports: 
 - name: http
   port: 80
   targetPort: 8080
   nodePort: 30050
   protocol: TCP