- name: Create file1
  copy:
    dest: /home/secret/file1.txt
    content: | # enable multi-line mode in yaml file
      Text Line1. in file1
      Text Line2. in file1
      Text Line3 {{ mytext }} #link to variable in file playbook.yml
- name: Create file2
  copy:
    dest: /home/secret/file2.txt
    content: |
      Text Line1. in file1 #create file with 3 lines
      Text Line2. in file1
      Text Line3 {{ mytext }}
